# Notepad Flow
1. Load libraries and settings
2. Analyze the hospital wait times dataset

In [4]:
# Loading Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# settings
sns.set(style='whitegrid', palette='Set2')
pd.set_option('display.max_columns', 50)
pd.set_option('display.float_format', lambda x: f'{x:.2f}')

# upload dataset and create path
DATA_PATH = Path(".")
HOSPITAL_FILE = DATA_PATH / "hospital_wait_times.csv"

In [5]:
hospital_df = pd.read_csv(HOSPITAL_FILE)
hospital_df.head(50)

,timestamp,patient_id,ward_location,priority,wait_time_min,nurse_on_duty
0,27/01/2026 10:47,P-3439,emergency,High,85.60,Nurse_Ratched
1,09/01/2026 20:44,P-8108,Pediatrics,High,54.42,Staff_B
2,25/01/2026 12:59,P-3100,emergency,URGENT,58.62,Nurse_Joy
3,17/01/2026 07:47,P-8699,Emergency,High,52.56,Staff_A
4,22/01/2026 06:15,P-4479,Peds,High,54.77,Staff_B
5,03/01/2026 05:00,P-2148,General Ward,urgent,40.21,Nurse_Joy
6,23/01/2026 21:59,P-9640,emergency,URGENT,32.28,Staff_B
7,10/01/2026 18:19,P-6702,Pediatrics,High,54.09,Staff_A
8,28/01/2026 09:36,P-9764,ER,Medium,14.73,Staff_B
9,11/01/2026 02:10,P-1007,General Ward,High,56.10,Staff_A
10,14/01/2026 03:09,P-6276,General Ward,Medium,52.93,Staff_A
11,23/01/2026 02:16,P-3963,Emergency,URGENT,36.16,Nurse_Joy
12,10/01/2026 15:59,P-3270,General Ward,Medium,47.83,Nurse_Ratched
13,15/01/2026 23:24,P-7100,Emergency,Medium,33.62,Nurse_Joy
14,20/01/2026 22:24,P-8374,Emergency,URGENT,31.00,Nurse_Ratched
15,04/01/2026 04:51,P-7640,General Ward,Medium,59.33,Nurse_Ratched
16,12/01/2026 14:48,P-8041,Emergency,urgent,47.86,Nurse_Joy
17,09/01/2026 19:08,P-7183,Emergency,Low,74.68,Staff_A
18,08/01/2026 07:56,P-1847,Pediatrics,URGENT,84.09,Nurse_Joy
19,05/01/2026 01:04,P-4873,emergency,High,55.25,Staff_A
20,21/01/2026 06:18,P-5401,ER,Medium,49.54,Staff_B
21,25/01/2026 10:55,P-7874,GW,URGENT,70.41,Nurse_Ratched
22,17/01/2026 16:20,P-2411,Emergency,Medium,19.41,Staff_A
23,09/01/2026 17:18,P-1107,General Ward,URGENT,27.61,Nurse_Ratched
24,22/01/2026 11:13,P-2996,General Ward,Low,42.98,Nurse_Ratched
25,15/01/2026 20:07,P-8036,General Ward,URGENT,50.86,Staff_B
26,11/01/2026 20:52,P-1086,emergency,High,47.50,Staff_B
27,30/01/2026 00:15,P-4199,ER,urgent,47.77,Nurse_Joy
28,19/01/2026 09:10,P-2075,General Ward,Low,57.12,Nurse_Joy
29,20/01/2026 05:16,P-6574,Emergency,Medium,46.09,Nurse_Ratched
30,10/01/2026 11:30,P-3324,ER,Low,54.58,Nurse_Joy
31,03/01/2026 20:43,P-3484,General Ward,High,49.94,Staff_B
32,20/01/2026 13:51,P-5191,Pediatrics,URGENT,37.54,Nurse_Ratched
33,22/01/2026 06:53,P-8542,ER,Low,33.69,Nurse_Ratched
34,14/01/2026 20:22,P-7211,Pediatrics,Medium,30.85,Staff_A
35,10/01/2026 15:18,P-3703,Emergency,URGENT,52.27,Staff_A
36,06/01/2026 01:02,P-8173,emergency,Medium,43.25,Staff_A
37,30/01/2026 16:28,P-2191,ER,urgent,73.53,Nurse_Ratched
38,29/01/2026 10:35,P-5054,ER,Low,48.57,Nurse_Ratched
39,15/01/2026 22:51,P-3481,ER,URGENT,74.95,Nurse_Joy
40,13/01/2026 03:59,P-8825,Peds,High,30.10,Nurse_Ratched
41,18/01/2026 23:04,P-3695,Pediatrics,urgent,47.95,Staff_A
42,18/01/2026 06:17,P-4765,Peds,Medium,27.95,Nurse_Ratched
43,11/01/2026 10:16,P-4123,General Ward,Low,45.01,Staff_B
44,20/01/2026 06:00,P-9243,ER,High,60.39,Nurse_Ratched
45,04/01/2026 11:56,P-6170,Emergency,High,42.65,Staff_A
46,19/01/2026 09:53,P-7845,GW,urgent,44.53,Staff_A
47,20/01/2026 01:03,P-1740,GW,urgent,54.75,Nurse_Joy
48,01/01/2026 07:08,P-4647,emergency,High,77.32,Nurse_Ratched
49,22/01/2026 02:56,P-9986,ER,Low,35.85,Staff_A

# Missing values

In [6]:
hospital_df.isna().sum().to_frame(name="missing_values")

               missing_values
timestamp                   0
patient_id                  0
ward_location               0
priority                    0
wait_time_min               0
nurse_on_duty               0